// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NameButtonSearchTriggerController from "./name_button_search_trigger_controller"
application.register("name-button-search-trigger", NameButtonSearchTriggerController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TestController from "./test_controller"
application.register("test", TestController)
